/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_espace_agent (void);
GtkWidget* create_reservation_hotel (void);
GtkWidget* create_facture_de_reservation (void);
GtkWidget* create_Login (void);
GtkWidget* create_fontselectiondialog1 (void);
GtkWidget* create_resultat_recherche_client (void);
GtkWidget* create_ajout_hotel (void);
GtkWidget* create_modifier_hotel (void);
GtkWidget* create_resultat_de_recherche_non_trouve (void);
GtkWidget* create_resultat_recherche_hotel_agent (void);
GtkWidget* create_first_interface (void);
GtkWidget* create_inscription_client (void);
GtkWidget* create_Espace_admin (void);
GtkWidget* create_Ajout_agent (void);
GtkWidget* create_Modifier_agent (void);
GtkWidget* create_profil_admin (void);
GtkWidget* create_Modifier_admin (void);
GtkWidget* create_espace_client (void);
GtkWidget* create_payer_hotels (void);
GtkWidget* create_payer_vols (void);
GtkWidget* create_payer_sejours (void);
GtkWidget* create_payer_location_voitures (void);
GtkWidget* create_profile (void);
GtkWidget* create_Modification_des_informations (void);
GtkWidget* create_window_ajouter_recmlamation (void);
GtkWidget* create_modifier_reclamation_client (void);
GtkWidget* create_window2 (void);
GtkWidget* create_historique_payer_hotels (void);
GtkWidget* create_modifier_payer_hotels (void);
